<?php
$paginator = $this->paginator;
$columns = array(
    'id' => 'Id',
    'code' => 'Code',
    'name' => 'Name',
);
?>
<table border="1">
    <thead>
        <tr>            
        <?php foreach($columns as $columnId => $columnLabel):?>
            <td><?php echo $columnLabel?></td>
        <?php endforeach;?>
            <td colspan=2>Actions</td>
        </tr>
    </thead>
    <tbody>
        <?php foreach($paginator as $item):?>
            <tr>                
                <?php foreach($columns as $columnId => $columnLabel):?>
                <td><?php echo $item[$columnId]?></td>
                <?php endforeach?>
                <td><a href="<?php echo $this->url('KapitchiLocation/Division/Update', array('id' => $item['id']))?>">Edit</a></td>
                <td><a href="<?php echo $this->url('KapitchiLocation/Division/Remove', array('id' => $item['id']))?>">Delete</a></td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>
<?php echo $this->paginationControl($paginator,
                            'Sliding',
                            'paginator'); ?>
